export enum EventActionType {
  SET_DATE = 'SET_DATE',
  ONCLICK_SELECTED = 'ONCLICK_SELECTED',
  SET_VISIBLE = 'SET_VISIBLE',
  SAVE_EVENT = 'SAVE_EVENT',
  CLEAR_EVENT = 'CLEAR_EVENT',
  UPDATE_EVENT = 'UPDATE_EVENT',
}
